# Generated by Django 2.2.9 on 2020-04-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Member'),
        ),
    ]
