# Generated by Django 2.2.9 on 2020-04-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('BOARD', 'Board'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20)),
                ('agenda', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('minutes', models.URLField()),
                ('resolutions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
